### ISSUE TITLE
Cumulative max number of samples?

### ISSUE THREAD

**Issue by getSurreal** [MajenkoLibraries/Average#5]
I'm attempting to keep averages of temperature and humidity.  I could do over 200 with a single Average.  With two Averages initiated, if I specify more than 140 samples my program fails to run.  It uploads and there aren't any errors.  If I try to initiate a 3rd average with 140 samples it fails again.  I didn't bother to find out what the max value for 3 Averages was, but if I set them to just 10 it works.

**Comment by getSurreal** [comment]
The limited amount of SRAM on an Arduino is the source of the problem.

**Comment by majenkotech** [comment]
Yeah, the RAM on an Uno is rather limited.  If you're using floats, that's 4 bytes per entry.  200 entries is 800 bytes.  With two averages at 140 floats that's (140 * 4 * 2) = 1120 - more than half the Uno's memory, and that's just for the data storage. You have the other required status and counter variables etc on top of that, plus whatever else you are doing in your sketch.
